# Simplified variant of https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment/docker-compose-keycloak.yaml
version: '3.0'
services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - './oauth2-proxy.cfg:/oauth2-proxy.cfg'
    restart: unless-stopped
    depends_on:
      - keycloak
    network_mode: host
    # required for oauth2-proxy.cfg - upstreams localhost, as the frontend isn't available inside docker

  # docker run -p 8080:8080 -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:26.2.5 start-dev
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2.5
    command: start-dev --http-port=9080
    hostname: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    ports:
      - 9080:9080/tcp

# NOTE: @dv-usama-ansari: Not sure if this is still needed, but it was required for the oauth2-proxy to work with keycloak as of jboss/keycloak v10.0.0 which does not exist anymore
# this docker image REALLY doesn't like to run in network-mode host
# requires this in your /etc/hosts (uncommented)
# 127.0.0.1 keycloak
# 127.0.0.1 oauth2-proxy
