name: build docker

on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up node version
        uses: actions/setup-node@v4
        with:
          node-version: '20.9'
      - name: Install dependencies
        run: yarn install --no-immutable --inline-builds
        shell: bash
      - name: Webpack build
        run: yarn run webpack:prod
        shell: bash
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/datavisyn/visyn_core
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/standalone/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}