name: build nightly

on:
  workflow_dispatch:
    inputs:
      cypress:
        description: 'Run cypress'
        required: false
        type: boolean
        default: false
  schedule:
    - cron: '15 1 * * *'

jobs:
  build-main:
    uses: datavisyn/github-workflows/.github/workflows/build-node-python.yml@new_deployment
    secrets: inherit
    with:
      cypress_enable: true
      cypress_run_because_flag: ${{ github.event_name == 'schedule' || inputs.cypress == true }}
      branch: main
  build-develop:
    uses: datavisyn/github-workflows/.github/workflows/build-node-python.yml@new_deployment
    secrets: inherit
    with:
      cypress_enable: true
      cypress_run_because_flag: ${{ github.event_name == 'schedule' || inputs.cypress == true }}
      branch: develop