name: build nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '15 1 * * *'

jobs:
  build-main:
    uses: datavisyn/github-workflows/.github/workflows/build-node-python.yml@new_deployment
    secrets: inherit
    with:
      cypress_enable: true
      cypress_run_because_flag: true
      branch: main
  build-develop:
    uses: datavisyn/github-workflows/.github/workflows/build-node-python.yml@new_deployment
    secrets: inherit
    with:
      cypress_enable: true
      cypress_run_because_flag: true
      branch: develop
