name: build

on:
  workflow_dispatch:
    inputs:
      cypress:
        description: 'Run cypress'
        required: false
        type: boolean
        default: false
  push:

jobs:
  build-hosted:
    uses: datavisyn/github-workflows/.github/workflows/build-node-python.yml@vdelev_selfhosted
    secrets: inherit
    with:
      cypress_enable: true
      cypress_run_because_flag: ${{ inputs.cypress == true }}
  build-selfhosted:
    needs: build-hosted
    if: always()
    uses: datavisyn/github-workflows/.github/workflows/build-node-python.yml@vdelev_selfhosted
    secrets: inherit
    with:
      runs_on: self-hosted
      cypress_enable: true
      cypress_runs_on: self-hosted
      cypress_run_because_flag: ${{ inputs.cypress == true }}
