name: build

on:
  workflow_dispatch:
    inputs:
      cypress:
        description: 'Run cypress'
        required: false
        type: boolean
        default: false
      chromatic:
        description: 'Run chromatic'
        required: false
        type: boolean
        default: false
  push:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: ${{ github.event_name != 'pull_request_review' || github.event.review.state == 'approved' }}
    uses: datavisyn/github-workflows/.github/workflows/build-node-python.yml@main
    secrets: inherit
    with:
      chromatic_enable: ${{ inputs.chromatic == true || github.event.review.state == 'approved' }}
      cypress_enable: true
      cypress_run_because_flag: ${{ inputs.cypress == true || github.event.review.state == 'approved' }}
