name: Chromatic UI test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    uses: datavisyn/github-workflows/.github/workflows/build-node.yml@main
    secrets: inherit
    with:
      chromatic_enable: true
