name: Chromatic UI test

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: ${{ github.event_name != 'pull_request_review' || github.event.review.state == 'approved' }}
    uses: datavisyn/github-workflows/.github/workflows/build-node.yml@main
    secrets: inherit
    with:
      chromatic_enable: true
