name: Create a new release PR

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: 'The next version to release'
        required: false
          
jobs:
  release:
    uses: datavisyn/github-workflows/.github/workflows/release-source.yml@feat-automate-releases-releasenotes
    secrets: inherit 
